huh_encore:
  encore:
    entries:
      - { name: "contao-tab-control-bundle", requiresCss: false, head: false, file: "vendor/heimrichhannot/contao-tab-control-bundle/src/Resources/assets/js/contao-tab-control-bundle.js" }
    legacy:
      js:
        - 'huh_contao-tab-control-bundle_bootstrap-tabs'
        - 'huh_contao-tab-control-bundle'